[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wen_wns_marketplace = "sALEeD9VGNquoGSXvUAKLeVbXdjiPCb3FTuTm1xSLod"
wen_new_standard = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"
wen_royalty_distribution = "diste3nXmK7ddDTs1zb6uday6j4etCa9RChD8fJ1xay"
wen_transfer_guard = "LockdqYQ9X2kwtWB99ioSbxubAmEi8o9jqYwbXgrrRw"

[programs.devnet]
wen_wns_marketplace = "sALEeD9VGNquoGSXvUAKLeVbXdjiPCb3FTuTm1xSLod"
wen_new_standard = "wns1gDLt8fgLcGhWi5MqAqgXpwEP1JftKE9eZnXS1HM"
wen_royalty_distribution = "diste3nXmK7ddDTs1zb6uday6j4etCa9RChD8fJ1xay"
wen_transfer_guard = "LockdqYQ9X2kwtWB99ioSbxubAmEi8o9jqYwbXgrrRw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/wen_royalty_distribution.test.ts"

[test]
startup_wait = 50000
shutdown_wait = 2000
upgradeable = false
